# .github/workflows/terraform.yml
name: Terraform Apply

on:
  push:
    paths:
      - 'First_instance_haier_account.tf'
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      # Uncomment below to apply changes automatically
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve